name: Self-test

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

  workflow_dispatch:
    inputs:
      test:
        type: boolean
        default: false
        description: A pointless checkbox.

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env

  wait:
    name: Wait
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: sleep 30
