name: Self-test

on:

  workflow_run:
    workflows: [Build]
    types:
      - completed

  workflow_dispatch:
    inputs:
      test:
        type: boolean
        default: false
        description: A pointless checkbox.

jobs:
  deploy:
    name: Deploy to Cloud via ArgoCD
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:

      - name: "Get PR number"
        id: get-pr-number
        uses: actions/checkout@v1
        # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - run: echo "Your PR is ${PR}"    
      